import ProductRow from "@/components/cart/ProductRow";
import BasicButton from "@/components/global/BasicButton";
import PageHead from "@/components/global/PageHead";

import { CartContext } from "@/context/cart";
import { ButtonContainer, Card, Container } from "@/styles/cart";
import { useRouter } from "next/router";
import { useContext } from "react";

export default function Cart () {
    const { products, total, clearCart } = useContext(CartContext);
    const router = useRouter();

    const handlePurchase = () =>{
        alert("You have completed your purchase. Your products are on the way!!");
        router.push("/");
        clearCart();
    }

    return(
        <>
            <PageHead title="Cart MySide | E-commerce" description={"Generated by create next app"} />
            
            <Container>
                <Card>
                    {
                       total > 0 ?
                            products.map((product) => {
                                return <ProductRow key={product.id} {...product}/>
                            })
                        :
                            <h3>You don't have products in your shopping cart</h3>
                    }

                    <ButtonContainer>
                        <BasicButton text={"Continue shopping"} action={() => router.push("/")}/>
                        {
                            total > 0 ?
                                <BasicButton text={"Complete purchase"} action={handlePurchase}/>
                            :
                                null
                        }
                    </ButtonContainer>
                </Card>
            </Container>
        </>
    )
}