import Head from "next/head";

import { Grid, ProductsContainer } from "./style";

import ProductCard from "@/components/home/ProductCard";

export async function getServerSideProps() {
  const res = await fetch(`https://fakestoreapi.in/api/products`);
  const data = await res.json();

  return {
    props: {
      products: data.products,
    },
  };
}

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>MySide | Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ProductsContainer>
        <Grid>
          { products.map(({id, title, description, image, price, discount}) => [
            <ProductCard key={id} id={id} title={title} description={description} image={image} price={price} discount={discount}/>
          ])}
        </Grid>
      </ProductsContainer>
    </>
  );
}
