import Head from "next/head";

import { Container, ProductCard, ProductsGrid } from "@/styles/home";
import Image from "next/image";

export async function getServerSideProps() {
  const res = await fetch(`https://fakestoreapi.com/products`);
  const data = await res.json();

  console.log(data);

  return {
    props: {
      products: data,
    },
  };
}

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>My Side</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Container>
        <ProductsGrid>
          { products.map((product) => [
            <ProductCard>
              <Image 
                src={product.image}
                width={200}
                height={200}
                alt={product.title}
              />
              <h2>{product.title}</h2>
              <p>{product.description}</p>
            </ProductCard>
          ])}
        </ProductsGrid>
      </Container>
    </>
  );
}
